import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

/**
 * Regenerate `src/lib/figma-dead-nodes.ts` from `docs/figma-node-ledger.md`.
 *
 * The ledger is filled in one `get_screenshot` call at a time and is still incomplete — 151 of the
 * 324 ids were unreachable when the Figma MCP quota cut the sweep off. So this file will be
 * regenerated at least once more, which is why it is a script and not a hand-written list.
 *
 * Usage: node scripts/dead-nodes.mjs
 */

const LEDGER = 'docs/figma-node-ledger.md'
const OUT = 'src/lib/figma-dead-nodes.ts'
const ROOTS = ['src', 'docs', 'public']

// Root-level files are scanned too, without recursing — `README.md` cites node ids in its
// `/dev/screens` table and two of them, `13:2307` and `13:2519`, are deleted. That is the first
// file a newcomer reads, and it sat outside the first version of this scan.
function rootFiles() {
  return readdirSync('.')
    .filter((entry) => !entry.startsWith('.'))
    .filter((entry) => statSync(entry).isFile())
}

// A naive `\d+:\d+` drags in clock strings — `08:12`, `12:36`, `00:01` live in `format.ts`,
// `useCountdown.ts` and `countdown.test.ts`. A node id has a non-zero first part and a 3-to-5
// digit second.
export const NODE_ID = /\b([1-9]\d*):(\d{3,5})\b/g

// The ledger lists every id by definition, the generated file lists every dead one, and the guard
// test names three of them in its docblock to say what it is for. Scanning any of the three would
// make the guard feed on its own output — measured: the first run flagged its own comment. The
// blind spot that buys is one file, and it is the file whose whole job is to fail on dead ids.
//
// `CLAUDE.md` is excluded for the same reason: its Bug-fixes section has to name `21:2896`,
// `13:2307` and `13:2519` to explain why this guard exists at all.
export const NOT_SCANNED = new Set([
  LEDGER,
  OUT,
  'CLAUDE.md',
  'src/lib/__tests__/figma-dead-nodes.test.ts',
])

export function* walk(dir) {
  for (const entry of readdirSync(dir)) {
    if (entry === 'node_modules' || entry.startsWith('.')) continue
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) yield* walk(full)
    else yield full
  }
}

export function citations(roots = ROOTS) {
  const found = new Map() // id -> Set of posix-style paths
  for (const root of [...roots, null]) {
    for (const file of root === null ? rootFiles() : walk(root)) {
      const rel = relative('.', file).replace(/\\/g, '/')
      if (NOT_SCANNED.has(rel)) continue
      if (/\.(png|jpg|jpeg|webp|ico|woff2?|pdf)$/i.test(rel)) continue
      let text
      try {
        text = readFileSync(file, 'utf8')
      } catch {
        continue
      }
      for (const match of text.matchAll(NODE_ID)) {
        const id = `${match[1]}:${match[2]}`
        if (!found.has(id)) found.set(id, new Set())
        found.get(id).add(rel)
      }
    }
  }
  return found
}

function deadFromLedger() {
  const dead = []
  for (const line of readFileSync(LEDGER, 'utf8').split('\n')) {
    const row = line.match(/^\| `([^`]+)` \| dead \| /)
    if (row) dead.push(row[1])
  }
  return dead
}

export function deadCitations() {
  const dead = deadFromLedger()
  const cited = citations()
  const accepted = []
  for (const id of dead) {
    for (const file of cited.get(id) ?? []) accepted.push(`${id} ${file}`)
  }
  return { dead, accepted: accepted.sort() }
}

// The guard test imports `citations` from this file, so generating must not happen on import.
if (process.argv[1] && process.argv[1].replace(/\\/g, '/').endsWith('scripts/dead-nodes.mjs')) {
  main()
}

function main() {
  const { dead, accepted } = deadCitations()

  const body = `// Generated by \`node scripts/dead-nodes.mjs\` from \`docs/figma-node-ledger.md\`. Do not edit by hand.
//
// Every id below was probed one at a time with the Figma MCP \`get_screenshot\` at
// \`maxDimension: 16\` and answered "The provided node ID was not found in the file". Neither a
// whole-page \`get_metadata\` dump nor a numeric range is admissible evidence here: both were tried
// in session 12 and both gave confident wrong answers.
//
// \`ACCEPTED_CITATIONS\` is a baseline, not an approval. Those ${accepted.length} citations were already in the tree
// when the guard was written; the guard exists to stop new ones. Removing a line from this list
// after cleaning up its citation is always safe — the guard never asks that a baseline entry still
// be present.

export const DEAD_NODE_IDS: readonly string[] = [
${dead.map((id) => `  '${id}',`).join('\n')}
]

export const ACCEPTED_CITATIONS: readonly string[] = [
${accepted.map((line) => `  '${line}',`).join('\n')}
]
`

  writeFileSync(OUT, body)
  console.log(`${OUT}: ${dead.length} dead ids, ${accepted.length} accepted citations`)
}
